{{- if .Values.backend.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "triviabackend.fullname" . }}
  labels:
    app.kubernetes.io/stack: {{ include "triviabackend.fullname" . }}
    {{- include "triviapp.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.backend.hpa.maxReplica }}
  minReplicas: {{ .Values.backend.hpa.minReplica }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "triviabackend-deployment.fullname" . }}
{{- with .Values.backend.hpa.metrics }}
  targetCPUUtilizationPercentage: {{ .Values.backend.hpa.targetCPU }}
{{- end }}
{{- end }}
---
{{- if .Values.frontend.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  {{ include "triviafrontend.fullname" . }}
  labels:
    app.kubernetes.io/stack: {{ include "triviafrontend.fullname" . }}
    {{- include "triviapp.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.frontend.hpa.maxReplica }}
  minReplicas: {{ .Values.frontend.hpa.minReplica }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "triviafrontend-deployment.fullname" . }}
{{- with .Values.frontend.hpa.metrics }}
  targetCPUUtilizationPercentage: {{ .Values.frontend.hpa.targetCPU }}
{{- end }}
{{- end }}